const API_PERMISSIONS =  {
    PUBLIC_ENDPOINT: "PUBLIC_ENDPOINT",
    INTERNAL_ENDPOINT: "INTERNAL_ENDPOINT",
    API_ENDPOINT: "API_ENDPOINT",
    CREATE_ME: "CREATE_ME",
    CREATE_ORGANISATION: "CREATE_ORGANISATION"
}
export default API_PERMISSIONS;
