name: QA Pipeline
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
env:
  NODE_VERSION: '18.x' # set this to the node version to use (supports 8.x, 10.x, 12.x)
  HELM_EXPERIMENTAL_OCI: 1

jobs:
  nodejs:
    runs-on: ubuntu-latest
    name: Validate nodejs
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2.2.0
        with:
          node-version: '20'
      - name: Install pnpm
        run: npm -g install pnpm
      - name: Install packages
        run: pnpm install
      - name: Install packages
        run: pnpm lint
      - name: Install packages
        run: pnpm test
  docker:
    runs-on: ubuntu-latest
    name: Validate docker
    steps:
      - uses: actions/checkout@v3
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1.6.0
        with:
          driver: docker
      - name: docker build
        run: docker build . -t "test-docker"
  helm:
    runs-on: ubuntu-latest
    name: Validate helm
    steps:
      - uses: actions/checkout@v3
      - name: helm lint
        run: helm lint ./charts
      - name: helm template
        run: helm template test ./charts
